### ISSUE TITLE
GEMINI_API_KEY unavailable ，OPENAI_API_KEY

### ISSUE THREAD

**Issue by zhangdz1** [alexfazio/viral-clips-crew#5]
I entered GEMINI-API_KEY and it prompted me that I cannot use it. I need OPENAI-API_KEY to be translated as I entered GEMINI-API_KEY and it prompted me that I cannot use it.

**Comment by alexfazio** [comment]
> I entered GEMINI-API_KEY and it prompted me that I cannot use it. I need OPENAI-API_KEY to be translated as I entered GEMINI-API_KEY and it prompted me that I cannot use it.

At this time, viral-clips-crew requires **both** Gemini and OpenAI API keys.

We plan to incorporate greater model flexibility in the future.

**Comment by zhangdz1** [comment]
I have integrated the Gemini API.

**Comment by alexfazio** [comment]
> I have integrated the Gemini API.

Have you tried using `OPENAI_API_KEY` instead of `OPENAI-API_KEY`?

The same applies for `GEMINI-API_KEY`, it should be `GEMINI_API_KEY`.
